config/routes.rb
Rails.application.routes.draw do

  resources :games do
    resources :players, only:[:create, :destroy]
    patch 'start'
  end
  post 'players/:id/roll', to: 'players#roll', as: 'players_roll'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/home/index", to: "home#index", as: "home"

  root to: "games#index"


end

app/models/game.rb
class Game < ApplicationRecord

  MAX_PLAYER = 5

  scope :unfinished, -> { where(winner: nil) }

  has_many :players, autosave: true
  belongs_to :board
  belongs_to :winner, optional: true, class_name: 'Player', foreign_key: 'player_id'

  validates :turn, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  accepts_nested_attributes_for :players

  def started?
    turn > 0 || players.first.turn > 0
  end

  def begin_turn
    players.each do |player| 
      if player.turn == turn
        steps = player.roll_dice

        if player.cell 
          current_index = board.cell_hash[player.cell]
          player.cell = board.cells[current_index + steps]
        else
          player.cell = board.cells[steps - 1]
        end

        save
      elsif player.turn < turn
        raise "#{player.name}'s turn: #{player.turn}, which is less than game's turn: #{turn}"        
      end
    end
  end

  def end_turn
    if players.where({ turn: turn - 1}).count == 0
      self.turn += 1

      # TODO : cell act is probably in the wrong plage
      # board.cells.each do |cell|
      #   cell.act
      # end
      save
    end
  end

  def update_player(player, steps)
    if player.cell 
      current_index = board.cell_hash[player.cell]
      cell_index = current_index + steps
      player.cell = board.cells[cell_index] if cell_index < board.cells.size
    else
      player.cell = board.cells[steps - 1]
    end
    
    player.turn += 1
    players << player

    end_turn
  end

  def current_player
    players.where({ turn: turn - 1 }).first || players.order("turn DESC").first
  end

  def current_player_name
    current_player.name if current_player
  end

  def next_player
    players.where({ turn: current_player.turn }).second || players.where({ turn: turn }).first
  end

  def next_player_name
    next_player.name if next_player
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :set_current_player, only: [:show]

  # GET /games
  # GET /games.json
  def index
    @games = Game.unfinished.all
    render layout: "application_hero"
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @players = Player.for_game(@game).order(:id)
    @player = Player.new

    #hard code board retrieval
    @board = board
  end

  # GET /games/new
  def new
    @game = Game.new(players: [Player.new])
    
    render layout: "application_hero"
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    # Hard code - board
    # @game.board = Board.first

    respond_to do |format|
      if @game.save
        player = @game.players.first
        # authorize record
        cookies.signed[:player_id] = player.id

        # update player cell, hard-coded board retrieval
        player.cell = board.cells.order(:id).first
        player.save

        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start
    @game = Game.find(params[:game_id])
    @game.turn = 1
    @game.save
    
    # Starts broadcasting that game is started
    ActionCable.server.broadcast(
      "game",
      operation: "start",
      game_id: @game.id,
      current_player_id: @game.current_player.id
    ) 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.fetch(:game, {}).permit(:board_id, players_attributes: [:name])
    end

    def set_current_player
      @current_player = current_player
    end

    def board
      Board.first
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def title(game, current_player)
    res = "Game ID #{game.id} "
    if current_player.present?
      res += " | Player: #{current_player.name}"
    end
    res
  end
end

app/views/games/_control.slim
.container-floating
  .card
    header.card-header
      p.card-header-title
        -if @game.current_player == @current_player
          span.panel-icon
            i.fa.fa-asterisk
        = @current_player.name
      a.card-header-icon
        i.fa.fa-angle-down
    .card-content
      .content
        p.center.player-move
          | (0 - 6)
        small.roll-dice.next-player 
          | Next: 
          = @game.next_player_name
    footer.card-footer
      = link_to "Roll", players_roll_path(@current_player), remote: true, method: :post, class: "card-footer-item #{"is-disabled" unless @game.started? && @game.current_player == @current_player}", id: "roll-dice"

app/views/games/_form.html.slim
.columns
  .column.is-half
    = render partial: "global/alert", locals: {obj: game}
    = form_for(game) do |f|
      / Select Board
      = f.label :board_game, class: "label"
      p.control
        span.select
          = f.collection_select(:board_id, Board.all, :id, :name)
      
      / Player Name
      = f.fields_for :players do |ff|
        = ff.label :name, class: "label"
        p.control
          = ff.text_field :name, class: "input is-primary", placeholder: "Barry Allen"

      p.control
        = f.submit class: "button is-primary"

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.slim
/! Command
.command-bar
  = link_to 'New Game', new_game_path, class: 'button is-primary'

/! List of games
- @games.in_groups_of(3).each do |group|
  .tile.is-ancestor
    - group.each do |game|
      - if game
        .tile.is-parent.is-vertical.is-4
          article.tile.is-child.notification.is-warning
            p.title 
              = link_to "Game #{game.id}", game
            p.subtitle #{game.board.name}
            p Players (#{game.players.size})
            
      /   .tile.is-parent
      /     article.tile.is-child.notification.is-warning
      /       p.title Game 2
      /       p.subtitle Game Description
      
      /   .tile.is-parent
      /     article.tile.is-child.notification.is-warning
      /       p.title Game 3
      /       p.subtitle Game Description
      / 

app/views/games/new.html.slim
h1.title New Game
h2.subtitle Enjoy your new game :)
hr

= render 'form', game: @game

= link_to 'Back', games_path

app/views/games/show.html.slim
h1.title= title(@game, @current_player)
.columns

  - if !@game.started? && @current_player.blank? && @players.count < Game::MAX_PLAYER
    .column.is-5
      nav.panel
        p.panel-heading ="New player"
        .notification
          = render partial: "players/form"

  .column.is-4
    nav.panel#players_panel
      p.panel-heading ="Players"

      - if @players.empty?
        p.has-text-centered = "No players"
        
      - @players.each do |player|
        = render partial: "players/entry", locals: {id: player.id, name: player.name,\
              player: @current_player.present? ? @current_player.id == player.id : false}
  .column.is-3
    .notification.has-text-centered
      p ="Maximum five players in a game"
      br
      p.control
        = link_to "Start Game", game_start_url(@game), remote: true, method: :patch, class: "button is-warning", id: "start-game", disabled: @game.started?

      - if @current_player.present?
        p.control
          = link_to "Leave Room", game_player_url(@game, @current_player), {method: :delete, class: "button is-danger"}

.notification
  h1.title =@board.name
  = render partial: "players/board", locals: {board: @board}

- if @current_player.present?
  = render partial: "control", locals: {current_player: @current_player, game: @game}

javascript:
  window.game = {id: #{@game.id}}

- if @current_player.present?
  javascript:
    window.player = {id: "#{@current_player.id}", name: "#{@current_player.name}" }